apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvvolume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/centos"
